---
kind: ReplicationController
apiVersion: v1
metadata:
    name: green
    labels:
        app: green
spec:
    replicas: 1
    selector:
        app: green
    template:
        metadata:
            labels:
                app: green
        spec:
            containers:
                - name: green
                  image: thuyvyv2tv/udacity-capstone-pj:v1.0.0
                  ports:
                      - name: http-server
                        containerPort: 80
